import type { Metadata } from "next"

// * Start - providers
import ReactQueryProvider from "@/providers/ReactQuery.provider"
import CacheProvider from "@/providers/Cache.provider"
// * End - providers

// ** Start - Css
import "./outputs.css"
import { CssBaseline } from "@mui/material"
// ** End - Css

export const metadata: Metadata = {
  title: "Koknus",
  description: "Generated by danial karshenas",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <head>
        <title>Koknus</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Koknus" />
        <link rel="icon" href="/images/favicon.ico" />
        <meta name="robots" content="noindex" />
      </head>

      <ReactQueryProvider>
        <CacheProvider>
          {/* <CssBaseline /> */}
          <body>{children}</body>
        </CacheProvider>
      </ReactQueryProvider>
    </html>
  )
}
